### ISSUE TITLE
レビューしたよ^^

### ISSUE THREAD

**Issue by kanaru-ssk** [yui-szk/ts_pre#1]
## main.ts

割と完璧だと思う。

強いていうなら`result`っていう関数名をもう少し機能が伝わりやすい名前に出来そう。
例 : `updateDom`、`reflectToHtml`、`showValue`など。
https://github.com/yui-szk/ts_pre_count/blob/f27474fc5d8b1a78bb2aee23c61a0db1a2a64bdf/src/main.ts#L4-L8

## index.html

`<link rel="stylesheet" href="/src/style.css" />`はhead内の方がいい。
理由 : 
bodyの最後に書くとcssが当たっていないhtmlがレンダリング→css反映
headに書くとcss読み込み→htmlレンダリング
htmlのレンダリングは速くなるが、一瞬ページがチラつく原因になるのでheadに書く。

### cssセレクタの順番をhtml登場順にする

特に理由がなければhtmlの上にある順にすると読みやすい。

```css
body {...}

h1 {...}

p {...}

button {...}
```

### 0pxは0に省略

特に問題はないが、`0px`は`0`と省略出来る。
2文字分データ量も抑えらる + その分表示高速化。今回はViteがbuild時に`0px`→`0`の変換をしてくれてる

### rgba()は16進数置き換え

出来るだけ16進数で色指定した方が文字数少ない。
今回はViteがbuild時に`rgba(102, 135, 214, 0.429)`→`#6687d66d`の変換をしてくれてる。(vite優秀すぎる)  
が、透明度を省略して`#becbee`の方が短い。

### marginにマイナスの値を避ける

どうしても必要な時以外はmarginにマイナス値は避けたい。他の要素の位置が予測しづらくなる。

## LightHouseテスト

問題なし。
`<meta name="description" content="説明文">`が無いのを指摘してくる位。

<img width="918" alt="スクリーンショット 0005-11-05 0 22 45" src="https://github.com/yui-szk/ts_pre_count/assets/62755970/0d685b96-5400-4504-a795-4fc4b9d3c3fc">

[lighthouseレポート](https://github.com/yui-szk/ts_pre_count/files/13257008/download.pdf)

## 総評

かなり綺麗に作れてた！お疲れ様〜！

**Comment by yui-szk** [comment]
ありがとうございますー！

ところでscriptタグはheadじゃなくても大丈夫なんですか？

**Comment by kanaru-ssk** [comment]
> ところでscriptタグはheadじゃなくても大丈夫なんですか？

### <script type="text/javascript">の場合
scriptタグをheadに持ってくると、htmlがレンダリングされる前にjavascriptが実行されて`document.getElementById("count-value")`とかがエラーする。

一応全ての処理を`window.onload`をトリガーに実行させればエラーは回避できるけどメリットはない。

ので、HTML操作系のjavascriptファイルについてはbodyタグの一番下がいい。

### <script type="module">の場合

常にhtmlがレンダリングされてから読み込まれるのでheadに書いてもbodyに書いてもほぼ変わらない。

ので、type="module"の場合はhead内に書いた方が見つけやすいし良さそう！

参考 : [count-value](https://ja.javascript.info/modules-intro#ref-112)
